# Site
name: Geospatial Science Blog
description: Qiusheng Wu, PhD
meta_description: "Geospatial Science Blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
google_analytics: 'UA-129680193-1'
disqus: 'giswqs'
mailchimp-list: 'https://wetlands.us12.list-manage.com/subscribe?u=0c562b225605d65c3bfb39ccf&id=db04dfd2f0'
permalink: /:year-:month-:day-:title

# Authors
authors:
  qiusheng:
    name: Qiusheng
    display_name: Qiusheng Wu
    gravatar: ccac61b9dd44d7120244b2700cb72256
    email: wqs@binghamton.edu
    web: http://wetlands.io
    twitter: https://twitter.com/giswqs
    description: "Assistant Professor of Geography at Binghamton University (SUNY)"
    
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
